### PR TITLE
/speaking update

### PR DESCRIPTION
**Pull request by KarolinaTEH**
- ticket id
- timeline
- 1 category renamed
- 1 category added
- gallery update
- FAQ questions added
- categories description added (using WidgetIconGrid)
- link to videos from last edition added

+ menu:
- schedule & presenters - hidden from Visitors

### CODE REVIEW

**Comment by KarolinaTEH** [comment]
@az I’ve created a SpeakersVideo composition for ‘link to videos from last edition’. If it should be done in some more efficient way please let me know

**Comment by az** [comment]
@KarolinaTEH bravissimo.... if there is a club of your fans/devoters let me enroll :)

2 things

1) 
E-commerce Berlin Expo | Berlin | February, 2024 2023-08-22 10-58-37

<Wrapper is primitive element  (to create custom compositions) and almost every widget (like WidgetPresenters...) has wrapper inside..... now you have doubled wrapper (one in code in speaking.js and others in elements inside that wrapper )

image
 
2) you have empty import {} at the top.... it should be removed

**Comment by az** [comment]
@KarolinaTEH a po polskiemu....

masz na gorze Wrapper... pozniej kolejny Wrapper (bo nie zamkniety zostal poprzedni...) i widgety ktore maja w sobie wrapper.... jesli chcesz taki efekt wizualny to oczywiscie jest to OK..... ale moze nie jest....... domkniecie pierwszego Wrappera trzeba by gdzies przeniesc wyzej :)

**Comment by KarolinaTEH** [comment]
dzięki, poprawione ;)

**Pull request merged**
