### PR TITLE
updates

### PR DESCRIPTION
**Pull request by KarolinaTEH**
- field 'location' added to visitor regform
- /visit/edit created

@az 
image
it seems to be validations.js problem, but i'm not able to send PR with changes to this file:

```
      location: Yup.string()
      .min(2, "Please select")
      .max(200, 'Please select')
.requireWhenRequired(requiredFieldNames, 'Please select one of the following'),
```
it'll be also needed for EGA

```
party_participant_type: Yup.string()
      .min(2, "Please select")
      .max(200, 'Please select')
.requireWhenRequired(requiredFieldNames, 'Please select one of the following'),
```
updated file: [validations.js.zip](https://github.com/ecommerceberlin/ecommerceberlin.com/files/13513560/validations.js.zip)

### CODE REVIEW

**Comment by az** [comment]
@KarolinaTEH 
thx. 
1) tweaked the rule for location (oneOf ... yes/no)
2) i can see that the expected link https://ecommerceberlin.com/recall/[[token]]?goto=/visit/edit - does not load the user so i must investigate what is NOT going on here

**Comment by KarolinaTEH** [comment]
2. it works https://ecommerceberlin.com/recall/74e6ff1c21b0cb4701956e25ee58c2d61421445b?goto=/visit/edit

**Comment by az** [comment]
@KarolinaTEH sometimes it works and sometimes not.... i think the reason is that /visit/  has catch-all option and /visit/whatever is being resolved by [code].js.... (so SOMETIMES /edit is not being picked as valid existing page/target)
i am moving /visit/[code] to /v/[code]

**Comment by az** [comment]
ok @KarolinaTEH .... i have pushed tweaked FormSuccess component

**Pull request merged**
